spring:
  application:
    name: spring-01-05

quiz:
  correct-answers-percent-to-pass: 60

resource:
  questions:
    - locale: en-EN
      file-name: questions.csv
    - locale: ru-RU
      file-name: questions_ru_RU.csv
  answers:
    - locale: en-EN
      file-name: answers.csv
    - locale: ru-RU
      file-name: answers_ru_RU.csv
  default-locale: en-EN
